#!/bin/bash

EXPECTED_ARGS=2
E_BADARGS=65

if [ $# -ne $EXPECTED_ARGS ]
    then
      echo "Usage: runparallel diam numprocs hostfile"
        exit $E_BADARGS
        fi
make tables
./executables/tables $1 $2
make parallel
mpirun --mca mpi_show_handle_leaks 1 -np $2 --hostfile ./test/hostfile ./executables/parallel $1
